version: "3.8"

services:
  database:
    container_name: ATRI_DB
    image: mongo
    restart: always
    volumes:
      - ./data_db:/data/db
  bot:
    container_name: ATRI_SERVER
    environment:
      - OSU_CLIENT_ID=
      - OSU_CLIENT_SECRET=
    build:
      context: .
      args:
        - MONGO_URL==mongodb://database
    ports:
      - "9999:8008"
    depends_on:
     - database